
# Flamingo application
Conf/App/Name: Flamingo
Conf/App/Version: 0.1.170111
Conf/App/Usage: |
  Usage: flamingo.phar [TASK] [OPTIONS]
  Execute a task in the flamingo.yml of the current folder

  Options:
    -h, --help       Display this help and exit
    -v, --version    Output version information and exit

# Log report and output
Conf/Log/Debug: false

# Keep old fields after new ones are mapped
Conf/Mapping/Keep: false

# Don't apply processor if field does not exist
Conf/Modify/MustExist: false

# Processes class aliases
Conf/Alias/Source: Sources, Src
Conf/Alias/Destination: Destinations, Dest
Conf/Alias/Modify: Process, Mod
Conf/Alias/Mapping: Map

# Parsers allowed extensions
# Be careful to not use the same extension for multiple parsers
Conf/Parser/Json: json, js
Conf/Parser/Csv: csv
Conf/Parser/Xml: xml
Conf/Parser/Excel: xls, xlsx
Conf/Parser/Yaml: yaml, yml
Conf/Parser/Db: db
Conf/Parser/Console: console