
# Flamingo application
Conf/App/Name: Flamingo
Conf/App/Version: 0.1.161001
Conf/App/Usage: |
  Usage: flamingo.phar [TASK] [OPTIONS]
  Execute a task in the flamingo.yml of the current folder

  Options:
    -h, --help       Display this help and exit
    -v, --version    Output version information and exit

# Log report and output
Conf/Log/Level: -1
Conf/Log/File: flamingo.log
Conf/Log/Debug: false

# Processes class aliases
Conf/Alias/Source: Sources, Src
Conf/Alias/Destination: Destinations, Dest
Conf/Alias/Modify: Process, Mod

# Parsers allowed extensions
# Be careful to not use the same extension for multiple parsers
Conf/Parser/Json: json, js
Conf/Parser/Csv: csv
Conf/Parser/Xml: xml
Conf/Parser/Excel: xls, xlsx
Conf/Parser/Yaml: yaml, yml