
# Log report and output
Conf/Log/Level: error
Conf/Log/File: flamingo.log
Conf/Log/Debug: false

# Processes class aliases
Conf/Alias/Source: Sources, Src
Conf/Alias/Destination: Destinations, Dest

# Readers allowed extensions
Conf/Reader/Json: json, js
Conf/Reader/Csv: csv
Conf/Reader/Xml: csv
Conf/Reader/Excel: xls, xlsx

# Empty default task
Flamingo/Task/Default: